# Generated by Django 2.0.2 on 2018-03-04 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=280)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('loan_amount', models.FloatField(blank=True, null=True)),
                ('interest_rate', models.FloatField(blank=True, null=True)),
                ('installment', models.FloatField(blank=True, null=True)),
                ('annual_inc', models.FloatField(blank=True, null=True)),
                ('dti', models.FloatField(blank=True, null=True)),
                ('delinq_2yrs', models.IntegerField(blank=True, null=True)),
                ('inq_last_6mths', models.IntegerField(blank=True, null=True)),
                ('open_acc', models.IntegerField(blank=True, null=True)),
                ('pub_rec', models.IntegerField(blank=True, null=True)),
                ('revol_bal', models.IntegerField(blank=True, null=True)),
                ('revol_util', models.FloatField(blank=True, null=True)),
                ('total_acc', models.IntegerField(blank=True, null=True)),
                ('home_ownership', models.CharField(blank=True, choices=[('MORTGAGE', 'Mortgage'), ('NONE', 'None'), ('OTHER', 'Other'), ('OWN', 'Own'), ('RENT', 'Rent')], max_length=50, null=True)),
                ('verification_status', models.CharField(blank=True, choices=[('NOT_VERIFIED', 'Not Verified'), ('SOURCE_VERIFIED', 'Source Verified'), ('VERIFIED', 'Verified')], max_length=50, null=True)),
                ('purpose', models.CharField(blank=True, choices=[('CAR', 'Car'), ('CREDIT_CARD', 'Credit Card'), ('DEBT_CONSOLIDATION', 'Debt Consolidation'), ('EDUCATIONAL', 'Educational'), ('HOUSE', 'House'), ('MAJOR_PURCHAGE', 'Major Purchase'), ('MEDICAL', 'Medical'), ('MOVING', 'Moving'), ('OTHER', 'Other'), ('RENEWABLE_ENERGY', 'Renewable Energy'), ('SMALL_BUSINESS', 'Small Business'), ('VACATION', 'Vacation'), ('WEDDING', 'Wedding')], max_length=50, null=True)),
                ('term', models.CharField(blank=True, choices=[('36', '36 Months'), ('60', '60 Months')], max_length=50, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
