# Generated by Django 2.0.2 on 2018-04-08 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_personal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='image',
        ),
    ]
