# Generated by Django 2.0.2 on 2018-03-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_personal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='annual_inc',
            field=models.FloatField(blank=True, help_text='The self-reported annual income provided by the borrower during registration.', null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='delinq_2yrs',
            field=models.IntegerField(blank=True, help_text="The number of 30+ days past-due incidences of delinquency in the borrower's credit file for the past 2 years", null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='dti',
            field=models.FloatField(blank=True, help_text='A ratio calculated using the borrower’s total monthly debt payments on the total debt obligations, excluding mortgage and the requested LC loan, divided by the borrower’s self-reported monthly income.', null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='inq_last_6mths',
            field=models.IntegerField(blank=True, help_text='The number of inquiries in past 6 months (excluding auto and mortgage inquiries)', null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='installment',
            field=models.FloatField(blank=True, help_text='The monthly payment owed by the borrower if the loan originates.', null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='interest_rate',
            field=models.FloatField(blank=True, help_text='Interest Rate on the loan', null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='loan_amount',
            field=models.FloatField(blank=True, help_text='The listed amount of the loan applied for by the borrower.', null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='open_acc',
            field=models.IntegerField(blank=True, help_text="he number of open credit lines in the borrower's credit file.", null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='pub_rec',
            field=models.IntegerField(blank=True, help_text='Number of derogatory public records', null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='revol_bal',
            field=models.IntegerField(blank=True, help_text='Total credit revolving balance', null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='revol_util',
            field=models.FloatField(blank=True, help_text='Revolving line utilization rate, or the amount of credit the borrower is using relative to all available revolving credit.', null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='total_acc',
            field=models.IntegerField(blank=True, help_text="The total number of credit lines currently in the borrower's credit file", null=True),
        ),
    ]
